export default {
  arrowParens: 'always',
  bracketSameLine: false,
  objectWrap: 'preserve',
  bracketSpacing: true,
  semi: true,
  experimentalOperatorPosition: 'start',
  experimentalTernaries: false,
  singleQuote: true,
  jsxSingleQuote: true,
  quoteProps: 'as-needed',
  trailingComma: 'all',
  singleAttributePerLine: false,
  htmlWhitespaceSensitivity: 'css',
  vueIndentScriptAndStyle: false,
  proseWrap: 'preserve',
  insertPragma: false,
  printWidth: 110,
  requirePragma: false,
  tabWidth: 2,
  useTabs: true,
  embeddedLanguageFormatting: 'auto',
  rangeStart: 0,
  cursorOffset: -1,
};
